# Converter XML para dataframe Pandas

Importar as biblitecas necessárias

In [2]:
import pandas as pd
import requests
from xmltopd import extract_dataframe
import nltk
import json
import numpy as np

## Função para inserção de categoria

In [1]:
def insert_category_and_tokenized_text(document: dict, category: str) -> dict:
    tokenized_text: list[str] = nltk.sent_tokenize(document.get("description", "No text"))
    
    document["description"] = "\n".join(tokenized_text)
    document["category"] = category
    
    return document

Fazer as requisições à API e destrinchar os XML.

In [16]:
news_categories: list[str] = [
    "brasil",
    "carros",
    "ciencia_e_saude",
    "concursos_e_emprego",
    "economia",
    "educacao",
    "loterias",
    "mundo",
    "musica",
    "natureza",
    "planeta-bizarro",
    "politica",
    "pop-arte",
    "tecnologia",
    "turismo-e-viagem"
]

news: list[dict] = []

for category in news_categories:
    news += [insert_category_and_tokenized_text(document=doc, category=category) for doc in extract_dataframe(
        requests.get("https://g1.globo.com/rss/g1/" + category + "/").text
    )]

news

SSLError: HTTPSConnectionPool(host='g1.globo.com', port=443): Max retries exceeded with url: /rss/g1/brasil/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

Criar um *dataframe* Pandas a partir dos dados

In [31]:
news_df: pd.DataFrame = pd.DataFrame(news)[["title", "description", "category"]].sample(frac=1)
news_df

,title,description,category
1112,Cientista e engenheiro de dados estão em alta ...,Com desafio de encontrar mão de obra qualif...,tecnologia
1105,Engenheira de dados desvenda desafios da área ...,Apesar de salários que podem passar de R$ 2...,tecnologia
60,Polícia invade festa de facção criminosa no Ce...,Com o grupo foram encontrados armas de fog...,brasil
438,Resultado da Mega-Sena: 47 apostas da região a...,"Já no sorteio da Lotofácil, apostadores de ...",loterias
338,"Unicamp 2025: veja quando será o vestibular, d...",Comissão responsável pelo processo seletivo...,educacao
...,...,...,...
66,Prefeitura abre processo para contratação de e...,Interessados devem entregar documentos de ...,brasil
237,Reforma tributária: imposto sobre herança ou d...,Texto da reforma prevê que imposto passe a ...,economia
37,Padre é atropelado por motorista embriagado pe...,Teste do etilômetro apontou resultado três...,brasil
536,Eclipse solar na América do Norte leva multidã...,Preços de hospedagem e passagens aéreas exp...,mundo
850,Mulher é presa após latir para cão policial no...,"Havia dois mandados de prisão contra ela, q...",planeta-bizarro

Escrever *dataset* em **csv**

In [3]:
news_df.to_csv("g1.csv")

NameError: name 'news_df' is not defined

In [7]:
news_df = pd.read_csv("g1.csv")
dict(news_df.iloc[0])

{'Unnamed: 0': 1112,
 'title': 'Cientista e engenheiro de dados estão em alta e têm salário que pode passar de R$ 20 mil; veja como entrar',
 'description': '   Com desafio de encontrar mão de obra qualificada, profissões seguem em alta em 2024 porque empresas valorizam cada vez mais o uso de dados na tomada de decisões.\nO g1 conversou com pessoas envolvidas nessas áreas para entender como está o mercado de trabalho.\nCientista e engenheiro de dados estão em alta e têm salário que pode passar de R$ 20 mil; veja como entrar\nArquivo pessoal\nNo universo da tecnologia da informação (TI), as áreas de cientista e engenheiro de dados são as atuais queridinhas do momento.\nElas oferecem salários realmente atrativos, mas encontram barreiras para procurar profissionais.\n➡️ Eis a explicação: elas são relativamente novas e fazem parte do boom da IA generativa.\nAs empresas estão atrás de quem realmente domina o assunto, mas são poucos aqueles que estão preparados.\nQuem já conseguiu se qualificar, passa a ficar mais exigente em relação às vagas.\nEsses profissionais muitas vezes são atraídos por companhias estrangeiras, que pagam em euro ou dólar, permitindo até que a pessoa trabalhe do Brasil.\nEsse tipo de oferta mais atraente faz com que o mercado interno tenha dificuldades para reter os talentos.\n"Quando vira sênior, você não quer mais trabalhar para companhias brasileiras porque dá para ganhar muito mais recebendo em dólar, e trabalhando do Brasil.\nEu já recebi uma proposta para receber US$ 7 mil por mês de uma empresa gringa", conta a engenheira de dados Gabrielle Azevedo, de 27 anos.\nOutra profissão relacionada é a de analista de dados.\nEla não tem tanta valorização como as outras duas nem remuneração tão alta, mas a possibilidade de crescimento profissional existe (entenda abaixo).\n"Dados são gerados e consumidos o tempo todo e qualquer área pode se beneficiar deles.\nIsso explica o porquê de estes setores estarem em alta", diz Bruna Zamith, cientista de dados da Amazon Brasil.\n"Hoje em dia, não tem como você fazer inteligência artificial sem ter dados.\nO engenheiro vai dar suporte, mas o cientista vai ter a habilidade de criar os modelos generativos, por exemplo", diz Suelane Garcia Fontes, coordenadora técnica do centro de ciência de dados do Insper.\nO g1 conversou com três profissionais que têm a mesma idade (27 anos), mas que estão em trajetórias e momentos de carreira diferentes.\nEles falam sobre suas experiências, desafios e como está o mercado de engenharia, ciência e análise de dados.\nO g1 também ouviu professores e uma cientista de dados da Amazon Brasil, que falam mais sobre o mercado e dão dicas para quem tem interesse em investir nessas carreiras.\nNesta reportagem, você saberá:\nO que fazem esses profissionais?\nE como está o salário?\nOnde posso trabalhar com dados?\nPreciso de formação profissional?\nCursos gratuitos e comunidades de dados \nO que dizem os profissionais\n🧑\u200d🔬 O que fazem esses profissionais?\n➡️ Um engenheiro de dados é responsável por projetar, construir e gerenciar a infraestrutura de dados de uma organização.\nEsse profissional garante que os dados sejam disponíveis, confiáveis e prontos para serem utilizados pelos demais times da empresa.\n➡️ O cientista de dados faz a análise dos dados obtidos pelo engenheiro e descobre coisas a partir deles.\nCom essas informações em mãos, ele vai trazer destaques e soluções.\nA estatística está muito presente no dia a dia dele.\nAlém disso, vale observar que o cientista trabalha mais próximo de inteligência artificial generativa, um tipo de IA capaz de criar novos conteúdos a partir de ferramentas como o ChatGPT.\n➡️ Já o analista vai usar os dados para preparar gráficos e gerar relatórios que ilustrem uma situação.\nEm outras palavras, ele traduz e transforma os dados em informações que apoiam a tomada de decisões de negócios pelo cientista, por exemplo.\n⚠️ Ainda existem outros profissionais com funções relacionadas a essas acima, como engenheiros de analytics, engenheiros de plataforma de dados, engenheiros de machine learning, especialistas em DataOps e por aí vai, explica Artemísia Weyl, professora de programação e de engenheira de dados.\n>>>Volte ao topo<<<\nLeia também:\nQuem é Elon Musk, bilionário que entrou na mira de Alexandre de Moraes\n🤑 E como está o salário?\nDados obtidos pelo g1 com a plataforma de empregos Catho mostram que a média salarial em 2024 do cientista de dados está em R$ 7.801, enquanto a do engenheiro fica em R$ 6.927.\nQuando olhamos para o analista, a média fica em R$ 3.094, segundo o Vagas.com.\nTanto o levantamento da Catho como o da Vagas.com foram feitos nos primeiros meses deste ano.\nFabio Maeda, diretor da unidade de candidatos da Catho, diz que houve aumento na média salarial de profissionais na área de dados entre 2023 e 2024.\n"Os cientistas e os engenheiros tiveram incremento salarial de 3% e 7%, respectivamente.\nIsso indica que as empresas estão investindo mais em estruturação, análise e engenharia de dados".\nPara a consultoria Robert Half, os números podem ser ainda maiores no caso do cientista de dados.\nO estudo divulgado no fim de 2023 mostrou que um iniciante, que ainda está se desenvolvendo, pode receber em média R$ 14.400.\nUm profissional intermediário pode tirar R$ 18.700 ao mês, enquanto os líderes têm uma remuneração de R$ 24.100.\n"Depois da pandemia, quando houve uma série de demissões, as empresas não queriam mais pagar aqueles salários altos.\nSó que depois elas voltaram a contratar, mas com salários menores.\nAinda assim, a remuneração para essas áreas está acima da média em relação a outras profissões", analisa Isabela Marinho Rangel, fundadora da comunidade Data & Analytics Fórum.\nNote que a pessoa que faz análise de dado tem média salarial menor em relação ao cientista e ao engenheiro.\nSegundo o profissional Raphael Pavan, isso acontece porque esse cargo é um pouco mais antigo, ao contrário do cientista e do engenheiro, que são novos (entenda mais abaixo).\n>>>Volte ao topo<<<\n🏢 Onde posso trabalhar com dados?\nAinda segundo a Robert Half, os setores que vão liderar as contratações de profissionais de dados este ano são bancos, indústrias, seguradoras, empresas de educação e de saúde.\nIsso também quer dizer que não existem limitações para estas três profissões.\nÉ possível encontrar oportunidades em empresas de varejo, alimentos, bebidas, comunicação, saúde, no setor do agronegócio, dentre outros.\nApesar disso, Bruna Zamith, da Amazon Brasil, faz um alerta sobre a falta de diversidade nessas áreas.\n"De alguma forma, os dados deveriam refletir a realidade.\nSó que, para que eles reflitam a realidade, é preciso diversidade de informações e tem que evitar vieses", diz.\n"E, para que isso aconteça, a gente precisa de pessoas diversas trabalhando com dados, o que ainda é inexistente na área", completa.\n>>>Volte ao topo<<<\n🎓 Preciso de formação profissional?\nAssim como em outras áreas da tecnologia da informação, especialistas dizem que a graduação nem sempre é o único caminho para trabalhar como analista, engenheiro ou cientista de dados.\nUm primeiro contato com cursos disponíveis na internet já é algo vantajoso e o estudo constante se torna essencial, porque tecnologia muda o tempo todo.\nSegundo especialistas ouvidos pelo g1, os cursos superiores podem ajudar a pessoa a ter uma base mais sólida.\n"Caso a pessoa não tenha graduação e queira atuar na área, ela precisa entrar em uma faculdade de estatística, ciência da computação ou atualmente no curso tecnólogo de ciência de dados, por exemplo", diz a professora especializada em dados Artemísia Weyl.\nEngenharia de computação, análise e desenvolvimento de sistemas, banco de dados, física ou matemática (estas últimas exigem complemento em TI, posteriormente) são outras graduações que podem ajudar.\n>>>Volte ao topo<<<\n🫧 Cursos gratuitos e comunidades de dados \nEdumi: trata-se de uma organização da sociedade civil (OSC) que tem como objetivo capacitar jovens de baixa renda para o mercado de tecnologia, com foco na área de dados.\nOferece conteúdos, exercícios e mentorias para os novatos.\nPyLadies: comunidade dedicada para mulheres que têm interesse em trabalhar com tecnologia e linguagem Python.\nRealiza encontros on-line e presencial sobre o tema.\nData Girls: comunidade que busca promover o aprendizado, networking e colaboração para mulheres na ciência de dados e na inteligência artificial.\nPossui grupos de discussões no Telegram e no Discord.\nPrograma de aprendizado do Data Analyst: pensado para quem pensa em atuar como analista de dados, esse curso gratuito do Google Cloud abordando temas como big data, machine learning, SQL, entre outros.\nPrograma de aprendizado do Data Engineer: outro curso gratuito do Google Cloud para quem tem interesse em engenharia de dados.\nAborda processamento de dados, criação de pipelines, fundamentos de big data e mais.\nAçaí com Dados: comunidade com grupo no WhatsApp para troca de ideias sobre o universo de dados e promover a profissão na região Norte do país.\n>>>Volte ao topo<<<\nO que dizem os profissionais \nGabrielle\nArquivo pessoal\nA brasiliense Gabrielle Azevedo, de 27 anos, é engenheira de dados no iFood.\nEla é responsável pela engenharia de plataformas, gerenciando a infraestrutura de ferramentas de visualização de dados da companhia.\nLá, ela começou como analista de dados, mas logo mudou para engenharia por recomendação de um chefe.\n"Ele falou que engenharia seria mais interessante para mim, e que eu tinha feito um bom trabalho até aqui, me estimulando a migrar", conta.\nA jovem é formada em engenharia de produção pela Universidade de Brasília (UnB), teve seu primeiro contato com dados em 2018, quando era estagiária da Empresa Brasileira de Pesquisa e Inovação Industrial (Embrapii).\nUm ano depois, ela começou a estagiar no Google, em São Paulo, onde atuava analisando dados dentro do setor de marketing, entre outras tarefas relacionadas.\nGabriele\nArquivo pessoal\nAtualmente, Gabrielle recebe cerca de R$ 11 mil com carteira assinada (CLT) e reconhece que o salário nesse setor é realmente alto.\nNo entanto, ela faz alguns alertas necessários para quem pensa em investir nessa profissão.\n"Eu acho que o mais difícil é você conseguir entrar na área.\nVocê precisa iniciar já sabendo de muita coisa, como construção de banco de dados, SQL, nuvem (cloud), versionamento de código e mais.\nÉ preciso ter uma certa experiência.\nA curva de aprendizado também é bem maior do que as outras áreas da TI", conta.\n"Eu gosto muito do que eu faço e da empresa onde trabalho, mas só no ano passado eu consegui parar em falar sobre demissão.\nA engenharia de dados cobra muito da gente", diz Gabrielle.\n"Parei de pensar em me demitir ao perceber que o mercado desacelerou, pagando menos em outros cargos.\nE a minha área está em alta e é muito difícil de entrar nela, ou seja, seria perder uma chance muito grande.\nEntão, só pensei que valeria a pena continuar tentando porque a empresa é ótima, meu time, também", completa.\nGustavo\nArquivo pessoal\nO paraense Gustavo Ramos, de 27 anos, é um cientista de dados, uma das profissões que mais está no auge no universo dos dados.\nEle trabalha como freelancer e sonha em conseguir uma oportunidade fixa com contrato CLT.\nGustavo é formado em matemática e chegou a dar aulas em uma escola.\nO domínio com números e estatísticas contribuiu para o aprendizado e migração para a ciência de dados.\nEle ainda passou a estudar a linguagem de programação Python e fez um curso técnico de ciência de dados.\nComo freelancer, quando há demanda, ele consegue tirar entre R$ 2.000 a R$ 2.200 por mês.\nO primeiro "job" com isso foi conquistado em 2023 para uma empresa de varejo, onde ele conseguiu tirar R$ 1.200.\n"Aqui na minha região, mesmo, não se encontra tanto emprego em dados.\nPor isso, eu tento procurar oportunidades remotas", conta Gustavo, que reside na cidade de Ananindeua, na região metropolitana de Belém.\nAssim como na engenharia de dados, as empresas têm dado preferência para profissionais mais experientes, revela Gustavo.\n"Para iniciantes, que é o meu caso, é um pouco mais complicado de encontrar vagas".\nRaphael Pavan\nArquivo pessoal\nO analista de dados Raphael Pavan, de 27 anos, vive em Campinas, no interior de São Paulo, e, hoje, trabalha para o banco Agibank.\nEle conta que, embora seja apaixonado pela profissão, reconhece que ela não é tão queridinha como as demais, quando se olha para a remuneração.\n"A nossa profissão existe há mais tempo em relação ao engenheiro e ao cientista.\nEntão, a galera que já manjava um pouco dados conseguia assumir o papel do analista, mas de modos bem diferentes, de forma simplificada", explica.\nSegundo Suelane, professora do Insper, o analista não faz modelagem e predições como o cientista, por exemplo.\n"O analista é um princípio e, de fato, é uma profissão mais comum porque ela já existia", confirma.\n"Apesar disso, o analista consegue ter um bom salário e tem bastante oportunidade no mercado.\nAs possibilidades de crescimento contam muito a favor, também.\nConsequentemente, o salário vai aumentando", diz Raphael.\nRaphael é formado em ciência da computação pela Universidade Estadual de Campinas (Unicamp) e trabalha com dados desde 2018, sempre como analista, incluindo estágios.\nPassou por várias instituições financeiras, por empresas de educação e startups.\nInicialmente, o seu objetivo não era trabalhar como analista de dados, já que buscou por vagas em ciência da computação.\nPor fim, ele acabou entrando no universo do analista, quando foi chamado para estagiar em uma empresa brasileira do setor financeiro, a Elo.\n"Eu me apaixonei de cara.\nComo estagiário, mesmo, eu já pude entregar bastante coisa legal.\nAli, eu já assumia responsabilidades do analista", conta.\nHoje, mais experiente, ele diz que esse profissional precisa conhecer bem o negócio em que ele atua.\nPor exemplo, se você trabalha para um banco, é importante estudar sobre mercado financeiro.\nSe for atuar para uma empresa de app de delivery, é importante analisar o comportamento do cliente na hora de pedir comida.\nRaphael também reforça que a pessoa que deseja entrar nessa área precisa saber se comunicar.\nO analista é quem vai chegar nas reuniões e fazer apresentações em público — traduzir o que os dados dizem.\n"E, claro, não importa se você quer ser analista, engenheiro ou cientista, você tem que saber SQL e linguagem Python, porque são fundamentais para trabalhar com dados.\nEu acho que, em breve, Python vai ser o novo \'inglês fluente obrigatório\' na nossa área", finaliza Pavan.\n>>>Volte ao topo<<<\nProgramação em alta: veja como começar no setor\xa0\nProgramação em alta: veja como começar no setor\xa0\nSegurança da informação em alta: veja como entrar no setor\nSegurança da informação em alta: veja como entrar no setor\n5 dicas para começar na carreira de TI\n5 dicas para começar na carreira de TI',
 'category': 'tecnologia'}

Escrever para arquivo

Caso não queira aleatorizar o tamanho dos arquivos, importe a lista com os seus tamanhos de um arquivo salvo. Caso contrário, não execute esta célula

In [76]:
number_docs_series_dict_train: dict = {}
number_docs_series_dict_test: dict = {}
number_docs_series_dict_validation: dict = {}

with open("number_docs_train.json") as f_in:
    number_docs_series_dict_train = json.load(f_in)
    
with open("number_docs_test.json") as f_in:
    number_docs_series_dict_test = json.load(f_in)
    
with open("number_docs_val.json") as f_in:
    number_docs_series_dict_test = json.load(f_in)
    
number_docs_series_dict_train

{'number_docs': [2,
  4,
  1,
  4,
  4,
  1,
  1,
  3,
  4,
  2,
  2,
  3,
  2,
  3,
  5,
  2,
  2,
  4,
  3,
  3,
  3,
  3,
  1,
  2,
  2,
  3,
  2,
  1,
  3,
  5,
  3,
  2,
  4,
  2,
  4,
  1,
  1,
  4,
  5,
  5,
  3,
  1,
  3,
  3,
  4,
  3,
  5,
  1,
  1,
  1,
  3,
  1,
  2,
  4,
  3,
  2,
  4,
  2,
  1,
  1,
  5,
  4,
  4,
  1,
  5,
  2,
  4,
  2,
  3,
  1,
  2,
  1,
  5,
  2,
  3,
  3,
  5,
  5,
  4,
  1,
  3,
  1,
  2,
  5,
  2,
  2,
  1,
  5,
  1,
  2,
  4,
  2,
  4,
  3,
  2,
  4,
  3,
  1,
  1,
  3,
  1,
  3,
  3,
  4,
  3,
  4,
  3,
  3,
  3,
  5,
  2,
  1,
  5,
  4,
  3,
  2,
  4,
  3,
  3,
  4,
  5,
  5,
  2,
  4,
  3,
  1,
  2,
  1,
  3,
  3,
  4,
  5,
  4,
  4,
  5,
  1,
  1,
  1,
  1,
  2,
  1,
  4,
  1,
  4,
  5,
  2,
  2,
  4,
  1,
  1,
  2,
  1,
  5,
  4,
  1,
  2,
  4,
  1,
  4,
  3,
  4,
  4,
  3,
  1,
  4,
  5,
  5,
  5,
  3,
  2,
  2,
  2,
  4,
  3,
  3,
  4,
  4,
  1,
  1,
  1,
  5,
  5,
  4,
  3,
  1,
  3,
  2,
  5,
  2,
  3,
  1,
  1,
  2,
  1,
  5,
  1,
  4,
  1,
  3,
  4,
  4,
  5,
  4,
  5,
  5,
  4,
  2,
  1,
  1,
  5,
  3,
  2,
  3,
  2,
  2,
  5,
  4,
  2,
  2,
  2,
  4,
  4,
  1,
  5,
  1,
  2,
  1,
  2,
  2,
  2,
  3,
  4,
  4,
  2,
  1,
  2,
  4,
  2,
  3,
  5,
  3,
  2,
  5,
  3,
  1,
  2,
  2,
  4,
  4,
  2,
  3,
  2,
  5,
  5,
  3,
  4,
  4,
  1,
  1,
  4,
  5,
  1,
  1,
  4,
  1,
  4,
  4,
  5,
  2,
  5,
  3,
  2,
  1,
  2,
  5,
  1,
  2,
  3,
  5,
  3,
  2,
  4,
  4,
  5,
  5,
  1,
  2,
  1,
  2,
  3,
  1,
  3,
  1,
  2,
  4,
  4,
  5,
  4,
  1,
  5,
  5,
  5,
  2,
  3,
  5,
  3,
  2,
  2,
  3,
  2,
  1,
  2,
  2,
  1,
  3,
  4,
  3,
  3,
  4]}

Importa *dataset* salvo e divide em conjuntos de treino, teste e validação.

In [42]:
import os, sys

sys.path.append("../utils")

from convert_segformer import generate_segformer_docs

news_df: pd.DataFrame = pd.read_csv("g1.csv")

train_df, test_df, val_df = np.split(news_df, [int(0.7 * len(news_df)), int(0.9 * len(news_df))])
train_df

/home/wsl/.pyenv/versions/3.11.6/lib/python3.11/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

,Unnamed: 0,title,description,category
0,1112,Cientista e engenheiro de dados estão em alta ...,Com desafio de encontrar mão de obra qualif...,tecnologia
1,1105,Engenheira de dados desvenda desafios da área ...,Apesar de salários que podem passar de R$ 2...,tecnologia
2,60,Polícia invade festa de facção criminosa no Ce...,Com o grupo foram encontrados armas de fog...,brasil
3,438,Resultado da Mega-Sena: 47 apostas da região a...,"Já no sorteio da Lotofácil, apostadores de ...",loterias
4,338,"Unicamp 2025: veja quando será o vestibular, d...",Comissão responsável pelo processo seletivo...,educacao
...,...,...,...,...
904,133,"Alagamento, inundação e queda de árvore: saiba...",Preço médio da modalidade cresceu em dois a...,carros
905,794,"Recém-descoberta, espécie de árvore gigante da...",Dipteryx hermetopascoaliana pode alcançar a...,natureza
906,337,Enem 2023: 'espelhos' da redação estão disponí...,"Inep libera, em todas as edições, a versão ...",educacao
907,1195,Golpe da vaquinha: veja momento em que mulher ...,Stephani Santos Barbosa também viu a própri...,tecnologia
908,40,Quase dois anos após matar grávida e roubar be...,Jovem foi morta em agosto de 2016.\nSeis pe...,brasil

Estatísticas do conjunto de treino

In [36]:
news_categories: list[str] = [
    "brasil",
    "carros",
    "ciencia_e_saude",
    "concursos_e_emprego",
    "economia",
    "educacao",
    "loterias",
    "mundo",
    "musica",
    "natureza",
    "planeta-bizarro",
    "politica",
    "pop-arte",
    "tecnologia",
    "turismo-e-viagem"
]

[{ "category": cat, "abs_frequency": list(train_df["category"]).count(cat), "rel_frequency": list(train_df["category"]).count(cat) / len(train_df)} for cat in news_categories]

[{'category': 'brasil',
  'abs_frequency': 71,
  'rel_frequency': 0.0781078107810781},
 {'category': 'carros',
  'abs_frequency': 68,
  'rel_frequency': 0.0748074807480748},
 {'category': 'ciencia_e_saude', 'abs_frequency': 0, 'rel_frequency': 0.0},
 {'category': 'concursos_e_emprego', 'abs_frequency': 0, 'rel_frequency': 0.0},
 {'category': 'economia',
  'abs_frequency': 72,
  'rel_frequency': 0.07920792079207921},
 {'category': 'educacao',
  'abs_frequency': 65,
  'rel_frequency': 0.07150715071507151},
 {'category': 'loterias',
  'abs_frequency': 71,
  'rel_frequency': 0.0781078107810781},
 {'category': 'mundo',
  'abs_frequency': 72,
  'rel_frequency': 0.07920792079207921},
 {'category': 'musica',
  'abs_frequency': 69,
  'rel_frequency': 0.07590759075907591},
 {'category': 'natureza',
  'abs_frequency': 75,
  'rel_frequency': 0.08250825082508251},
 {'category': 'planeta-bizarro',
  'abs_frequency': 74,
  'rel_frequency': 0.0814081408140814},
 {'category': 'politica',
  'abs_frequency': 72,
  'rel_frequency': 0.07920792079207921},
 {'category': 'pop-arte',
  'abs_frequency': 65,
  'rel_frequency': 0.07150715071507151},
 {'category': 'tecnologia',
  'abs_frequency': 67,
  'rel_frequency': 0.0737073707370737},
 {'category': 'turismo-e-viagem',
  'abs_frequency': 68,
  'rel_frequency': 0.0748074807480748}]

In [78]:
merged_texts_df_train: pd.DataFrame = generate_segformer_docs(
    dataframe=train_df, 
    folder="train", 
    text_body_field="description", 
    max_doc_size=5, 
    category_field="category",
    number_docs_list=list(number_docs_series_dict_train.get("number_docs", []))
)

merged_texts_df_train

,fulltext,number_sentences,number_words,number_docs,average_words_per_sentence,median_words_per_sentence
0,Com desafio de encontrar mão de obra qualif...,166,3873,2,23.331325,21.0
1,Com o grupo foram encontrados armas de fog...,64,1603,4,25.046875,21.0
2,"Sorteio acontece no dia 30 de março, às 20h...",14,279,1,19.928571,19.5
3,Veja fotos da festa em Kiev: A capital da U...,125,3405,4,27.240000,24.0
4,Modelo foi usado em desfile na semana da mo...,113,2930,4,25.929204,22.0
...,...,...,...,...,...,...
314,"Segundo instituições financeiras, instabili...",63,1599,3,25.380952,23.0
315,"O britânico e brasileiro Noah Faria, filho ...",107,3467,4,32.401869,26.0
316,Recursos do programa de descontos no carro ...,73,2377,3,32.561644,28.0
317,Preço médio da modalidade cresceu em dois a...,80,2062,3,25.775000,24.5
318,Stephani Santos Barbosa também viu a própri...,47,1231,4,26.191489,21.0

Estatísticas do conjunto de teste

In [44]:
merged_texts_df_test: pd.DataFrame = generate_segformer_docs(
    dataframe=test_df, 
    folder="test", 
    text_body_field="description", 
    max_doc_size=5, 
    category_field="category",
    number_docs_list=list(number_docs_series_dict_test.get("number_docs", []))
)

merged_texts_df_test

,fulltext,number_sentences,number_words,number_docs,average_words_per_sentence,median_words_per_sentence
0,Neologismo que expressa um R&B de sotaque b...,69,1874,4,27.159420,24.0
1,Óculos da Apple oferecem sensação de imersã...,143,4342,4,30.363636,27.0
2,"Caso curioso ocorreu em Marlborough, Massac...",36,1079,2,29.972222,32.5
3,Animal vai ficar sob os cuidados de uma ent...,68,2183,4,32.102941,26.5
4,Informações foram divulgadas nesta sexta p...,30,904,2,30.133333,25.5
...,...,...,...,...,...,...
84,"A escritora, que vive em Edimburgo, é conhe...",155,4267,5,27.529032,24.0
85,"Felipe Gamba, dono do hostel localizado em ...",185,4421,5,23.897297,23.0
86,"Anfavea espera que as vendas de carros, com...",78,2046,3,26.230769,21.0
87,Candidatos de todo o mundo podem se inscrev...,57,1550,3,27.192982,26.0
88,"Ao todo, 249 apostas acertaram cinco número...",35,1034,3,29.542857,24.0

Estatísticas do conjunto de validação.

In [45]:
merged_texts_df_val: pd.DataFrame = generate_segformer_docs(
    dataframe=val_df, 
    folder="validation", 
    text_body_field="description", 
    max_doc_size=5, 
    category_field="category",
    number_docs_list=list(number_docs_series_dict_val.get("number_docs", []))
)

merged_texts_df_val

,fulltext,number_sentences,number_words,number_docs,average_words_per_sentence,median_words_per_sentence
0,"Homem, de 51 anos, não teve a identidade d...",11,153,1,13.909091,11.0
1,Música composta em 1978 por Renato Russo (1...,31,864,3,27.870968,23.0
2,As apostas podem ser feitas até as 19h em l...,153,4472,5,29.228758,26.0
3,Mais do que preparar os alunos para serem ...,7,264,1,37.714286,34.0
4,Um dos filmes mais aguardados do ano teve ...,129,3147,5,24.395349,22.0
5,Plenário da Casa pode manter ou revogar pri...,175,4854,4,27.737143,25.0
6,Assessor especial de Lula para assuntos in...,67,1668,3,24.895522,24.0
7,"Com as mudanças, atendimento poderá acontec...",33,869,3,26.333333,25.0
8,"Bilionário, que no fim de semana ameaçou de...",58,1708,2,29.448276,25.5
9,"""Ela me deixou..."".\nCantado duas vezes em ...",23,641,2,27.869565,21.0
10,"Cartunista e desenhista morreu aos 91 anos,...",133,3358,4,25.248120,23.0
11,Conferência de Quebec reuniu líderes dos pa...,74,2291,4,30.959459,26.0
12,Bairro carioca imortalizado no cancioneiro ...,53,1398,3,26.377358,21.0
13,Proposta aprovada pela Comissão de Assuntos...,112,3045,5,27.187500,22.0
14,Galileu Machado (PMDB) diz que cogita escal...,44,1329,2,30.204545,30.0
15,"A moeda norte-americana subiu 0,29%, cotada...",47,1118,1,23.787234,23.0
16,Resultado também foi influenciado pela meno...,28,859,1,30.678571,30.0
17,Dono da loja na Virgínia afirma que eles te...,8,190,1,23.750000,24.0
18,"João Brant disse, em entrevista à GloboNews...",67,2054,3,30.656716,25.0
19,Números obtidos por meio da Lei de Acesso à...,130,3844,3,29.569231,24.5
20,"Projeto Titan, que visava criar o veículo, ...",23,641,2,27.869565,20.0
21,Elba Ramalho e Luan Forró Estilizado\nRepro...,4,121,1,30.250000,27.5
22,Agosto foi o primeiro mês sem efeitos claro...,123,3270,3,26.585366,25.0
23,Fabricantes estão investindo bilhões de dól...,134,3245,5,24.216418,22.5
24,Nos pontos de atendimento serão oferecidos ...,118,3303,5,27.991525,24.0
25,Imagens em tempo real feitas de locais próx...,154,4011,5,26.045455,24.5
26,Houve um tempo em que as relações entre os ...,63,1842,1,29.238095,29.0
27,Ministério da Agricultura reconheceu que un...,107,2853,5,26.663551,22.0
28,Relator acolheu pedido do MEC e ampliou ens...,49,1576,1,32.163265,32.0
29,Umidade relativa do ar segue baixa e pode c...,41,1255,3,30.609756,25.0
30,Lista de aprovados foi divulgada às 15h des...,44,1368,2,31.090909,27.0
31,Ministro do STF entendeu que é preciso faz...,33,1596,3,48.363636,26.0
32,"Nem bem chegou da Europa, onde apresentou c...",71,2481,3,34.943662,34.0
33,Ranking anual é montado com base nas avalia...,107,3107,4,29.037383,22.0
34,Uma pessoa morreu e cinco foram hospitaliza...,153,3593,4,23.483660,21.0
35,Apostas podem ser feitas até as 19h em loté...,18,455,1,25.277778,24.5
36,"Mais recente episódio da série médica, exib...",82,2386,2,29.097561,24.0
37,"Parque Nacional do Iguaçu, que abriga as Ca...",140,3720,3,26.571429,25.5
38,Outras 97 apostas do estados acertaram quat...,15,305,1,20.333333,19.0
39,"Com o avanço da tecnologia, é cada vez mais...",129,3841,5,29.775194,25.0
40,Ave disse vários palavrões enquanto era ret...,14,288,2,20.571429,14.5
41,Veja quatro capas de álbuns criadas pelo de...,82,2389,4,29.134146,23.0
42,Organização confirmou que solenidade com au...,93,2548,4,27.397849,22.0
43,Interessados devem entregar documentos de ...,43,1892,2,44.000000,27.0
44,Teste do etilômetro apontou resultado três...,21,446,1,21.238095,18.0
45,Preços de hospedagem e passagens aéreas exp...,51,1326,4,26.000000,23.0

In [56]:
merged_texts_df_train["number_docs"].sum()

911

In [74]:
list(merged_texts_df_val["number_docs"]).count(1)

11

## Salvar tamanhos de arquivos em arquivo JSON.

In [47]:
with open("number_docs_train.json", 'w') as fp:
    json.dump({ "number_docs": list(merged_texts_df_train["number_docs"])}, fp)
with open("number_docs_test.json", 'w') as fp1:
    json.dump({ "number_docs": list(merged_texts_df_test["number_docs"])}, fp1)
with open("number_docs_val.json", 'w') as fp2:
    json.dump({ "number_docs": list(merged_texts_df_val["number_docs"])}, fp2)